# Set theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://mydomain.com'
baseurl: ''
title: 'IT Society'
description: 'Empowerment through technology'
permalink: pretty
avatarurl: 'https://gravatar.com/avatar/fba3bd65ae066575bed2847d64db94ce'
# logo: "https://gravatar.com/avatar/fba3bd65ae066575bed2847d64db94ce"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
  Home: /
  Blog: /blog/
  Events: /events/
  Our Partners: /partners/
  Logo: /
  MadeByStudents: /MadeByStudents/
  Join Us: /joinUs/
  Contact Us: /contact/


# Footer nav
navigation_footer:
  Back to top: ""

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: ""
    feature_text: ""
    feature_text_desc: "Blog"
    feature_image: "/assets/bg/clean-gray-paper.png"

  events:
    title: Events
    output: true
    description: ""
    feature_text: ""
    feature_text_desc: "Events"
    feature_image: "/assets/bg/brushed-alum-dark.png"

  partners:
    title: Our Partners
    output: true
    description: ""
    feature_text: ""
    feature_text_desc: "Our Partners"
    feature_image: "/assets/bg/always-grey.png"

  MadeByStudents:
    title: MadeByStudents
    output: true
    description: ""
    feature-text: ""
    feature_text_desc: "#MadeByStudents"
    feature_image: "/assets/bg/clean-gray-paper.png"

  joinUs:
    title: Join Us
    output: true
    description: ""
    feature-text: ""
    feature_text_desc: "Join Us"
    feature_image: "/assets/bg/clean-gray-paper.png"

   

