# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://mydomain.com'
baseurl: ''
title: 'IT Society'
description: 'Empowerment through technology'
permalink: pretty
# logo: "https://gravatar.com/avatar/fba3bd65ae066575bed2847d64db94ce"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
  Home: /
  Blog: /blog/
  Events: /events/
  Our Partners: /partners/
  Logo: //
  MadeByStudents: /made-by-students/
  Join Us: /join-us/
  Contact Us: /contact/


# Footer nav
navigation_footer:
  Back to top: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: ""
    feature_text: |
      Welcome to my blog
    feature_image: "https://picsum.photos/2560/600?image=866"
